// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlqQEjydG19bI57RxZltkDUYOjXFh_ew',
    appId: '1:142520805243:web:9fb60cab192f3a28b2ffde',
    messagingSenderId: '142520805243',
    projectId: 'pp-stream',
    authDomain: 'pp-stream.firebaseapp.com',
    storageBucket: 'pp-stream.appspot.com',
    measurementId: 'G-04PDLHRQHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrcd70zlz5kjlP4AGKYp-pz7CKRkUv4xY',
    appId: '1:142520805243:android:aea1d95f2ef7b108b2ffde',
    messagingSenderId: '142520805243',
    projectId: 'pp-stream',
    storageBucket: 'pp-stream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnFO6vzGNe96M5DqTZ09eMLb4fIYkzvWc',
    appId: '1:142520805243:ios:c592a6acdd6c3be7b2ffde',
    messagingSenderId: '142520805243',
    projectId: 'pp-stream',
    storageBucket: 'pp-stream.appspot.com',
    iosClientId: '142520805243-ubt2fc2l1ub9omv8ru2diduqjo8t7k5u.apps.googleusercontent.com',
    iosBundleId: 'com.ppstream.mobileApp',
  );
}
